name: e2e

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - uses: docker/build-push-action@v2
        with:
          context: e2e-test
      - run: docker buildx inspect
